import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generateAttendanceExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    // Create Summary Sheet
    const summaryData = [
        ["ATTENDANCE REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["SUMMARY METRICS"],
        ["Metric", "Value"],
        ["Total Employees", data.summary?.totalEmployees || 0],
        ["Average Working Hours", `${(data.summary?.avgWorkingHours || 0).toFixed(1)} hrs`],
        ["On-Time Rate", `${(data.summary?.onTimeRate || 0).toFixed(1)}%`],
        ["Total Distance", `${(data.summary?.totalDistance || 0).toFixed(1)} km`],
        [
            "Total Expenses",
            `₹${(data.summary?.totalExpenses || 0).toLocaleString()}`,
        ],
        ["Completed Shifts", data.summary?.completedShifts || 0],
        ["Active Shifts", data.summary?.activeShifts || 0],
        ["Total Working Hours", `${(data.summary?.totalWorkingHours || 0).toFixed(1)} hrs`],
        [""],
    ];

    // Add filter info if applied
    if (filters) {
        if (filters.employeeId) {
            summaryData.push([
                "Filter: Employee",
                data.employees?.find((e: any) => e.id === filters.employeeId)?.name ||
                "All",
            ]);
        }
        if (filters.department) {
            summaryData.push(["Filter: Department", filters.department]);
        }
        summaryData.push([""]);
    }

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

    // Style the summary sheet
    const summaryRange = XLSX.utils.decode_range(summarySheet["!ref"] || "A1");

    // Set column widths
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 20 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    // Add styling metadata (Note: basic xlsx doesn't support full styling, but we set the structure)
    summarySheet["A1"] = { v: "ATTENDANCE REPORT", t: "s" };
    summarySheet["A6"] = { v: "SUMMARY METRICS", t: "s" };

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Employee Statistics Sheet
    if (data.employeeStats && data.employeeStats.length > 0) {
        const employeeStatsData = [
            [
                "Employee Name",
                "Employee Number",
                "Department",
                "Days Present",
                "Avg Hours/Day",
                "On-Time %",
                "Total Distance (km)",
                "Total Expenses (₹)",
                "Completed Shifts",
                "Active Shifts",
            ],
        ];

        data.employeeStats.forEach((emp: any) => {
            employeeStatsData.push([
                emp.employeeName || "",
                emp.employeeNumber || "",
                emp.department || "",
                emp.daysPresent || 0,
                (emp.avgHours || 0).toFixed(1),
                (emp.onTimePercentage || 0).toFixed(1),
                (emp.totalDistance || 0).toFixed(1),
                (emp.totalExpenses || 0).toLocaleString(),
                emp.shiftStatus?.completed || 0,
                emp.shiftStatus?.active || 0,
            ]);
        });

        const employeeStatsSheet = XLSX.utils.aoa_to_sheet(employeeStatsData);

        // Set column widths
        employeeStatsSheet["!cols"] = [
            { wch: 25 }, // Employee Name
            { wch: 15 }, // Employee Number
            { wch: 20 }, // Department
            { wch: 12 }, // Days Present
            { wch: 15 }, // Avg Hours
            { wch: 12 }, // On-Time %
            { wch: 18 }, // Distance
            { wch: 18 }, // Expenses
            { wch: 15 }, // Completed
            { wch: 15 }, // Active
        ];

        XLSX.utils.book_append_sheet(workbook, employeeStatsSheet, "Employee Stats");
    }

    // Create Daily Statistics Sheet
    if (data.dailyStats && data.dailyStats.length > 0) {
        const dailyStatsData = [
            [
                "Date",
                "Present Count",
                "On-Time Count",
                "Total Hours",
                "Total Distance (km)",
                "Total Expenses (₹)",
                "Completed Shifts",
                "Incomplete Shifts",
            ],
        ];

        data.dailyStats.forEach((day: any) => {
            dailyStatsData.push([
                day.date || "",
                day.presentCount || 0,
                day.onTimeCount || 0,
                (day.totalHours || 0).toFixed(1),
                (day.totalDistance || 0).toFixed(1),
                (day.totalExpenses || 0).toLocaleString(),
                day.completedShifts || 0,
                day.incompleteShifts || 0,
            ]);
        });

        const dailyStatsSheet = XLSX.utils.aoa_to_sheet(dailyStatsData);

        // Set column widths
        dailyStatsSheet["!cols"] = [
            { wch: 15 },
            { wch: 15 },
            { wch: 15 },
            { wch: 12 },
            { wch: 18 },
            { wch: 18 },
            { wch: 18 },
            { wch: 18 },
        ];

        XLSX.utils.book_append_sheet(workbook, dailyStatsSheet, "Daily Stats");
    }

    // Create Leave Information Sheet
    if (data.leaveInfo && data.leaveInfo.length > 0) {
        const leaveData = [
            [
                "Employee Name",
                "Employee Number",
                "Department",
                "Start Date",
                "End Date",
                "Days Count",
                "Leave Type",
                "Paid/Unpaid",
                "Reason",
            ],
        ];

        data.leaveInfo.forEach((leave: any) => {
            leaveData.push([
                leave.employeeName || "",
                leave.employeeNumber || "",
                leave.department || "",
                leave.startDate || "",
                leave.endDate || "",
                leave.daysCount || 0,
                leave.leaveType || "",
                leave.isPaid ? "Paid" : "Unpaid",
                leave.reason || "",
            ]);
        });

        const leaveSheet = XLSX.utils.aoa_to_sheet(leaveData);

        // Set column widths
        leaveSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 20 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 20 },
            { wch: 12 },
            { wch: 30 },
        ];

        XLSX.utils.book_append_sheet(workbook, leaveSheet, "Leave Records");
    }

    // Create Regularization Sheet
    if (data.regularizationInfo && data.regularizationInfo.length > 0) {
        const regularizationData = [
            [
                "Employee Name",
                "Employee Number",
                "Request Date",
                "Request Type",
                "Original Start",
                "Original End",
                "Requested Start",
                "Requested End",
                "Reason",
                "Status",
                "Approved At",
            ],
        ];

        data.regularizationInfo.forEach((reg: any) => {
            const formatTime = (timeStr: string | null) => {
                if (!timeStr) return "N/A";
                try {
                    return format(new Date(timeStr), "HH:mm");
                } catch {
                    return timeStr;
                }
            };

            regularizationData.push([
                reg.employeeName || "",
                reg.employeeNumber || "",
                reg.requestDate || "",
                reg.requestType?.replace(/_/g, " ").toUpperCase() || "",
                formatTime(reg.originalStartTime),
                formatTime(reg.originalEndTime),
                formatTime(reg.requestedStartTime),
                formatTime(reg.requestedEndTime),
                reg.reason || "",
                reg.status || "",
                reg.approvedAt
                    ? format(new Date(reg.approvedAt), "MMM dd, yyyy")
                    : "Pending",
            ]);
        });

        const regularizationSheet = XLSX.utils.aoa_to_sheet(regularizationData);

        // Set column widths
        regularizationSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 12 },
            { wch: 20 },
            { wch: 15 },
            { wch: 15 },
            { wch: 15 },
            { wch: 15 },
            { wch: 30 },
            { wch: 12 },
            { wch: 15 },
        ];

        XLSX.utils.book_append_sheet(
            workbook,
            regularizationSheet,
            "Regularizations",
        );
    }

    // Create Detailed Attendance Sheet (if employeeAttendanceData exists)
    if (data.employeeAttendanceData && data.employeeAttendanceData.length > 0) {
        const detailedData = [
            [
                "Employee Name",
                "Employee Number",
                "Date",
                "Day of Week",
                "Status",
                "Shift Start",
                "Shift End",
                "Hours Worked",
                "Distance (km)",
                "Expenses (₹)",
                "Leave Type",
            ],
        ];

        data.employeeAttendanceData.forEach((empData: any) => {
            empData.dailyRecords?.forEach((record: any) => {
                const firstShift = record.shifts && record.shifts[0];
                detailedData.push([
                    empData.name || "",
                    empData.employeeNumber || "",
                    record.date || "",
                    record.dayOfWeek || "",
                    record.status || "",
                    firstShift?.startTime || "-",
                    firstShift?.endTime || "-",
                    record.summary?.totalHours
                        ? `${record.summary.totalHours.toFixed(1)} hrs`
                        : "-",
                    record.summary?.totalDistance
                        ? record.summary.totalDistance.toFixed(1)
                        : "-",
                    record.summary?.totalExpenses
                        ? record.summary.totalExpenses.toLocaleString()
                        : "-",
                    record.leave?.leaveType || "-",
                ]);
            });
        });

        const detailedSheet = XLSX.utils.aoa_to_sheet(detailedData);

        // Set column widths
        detailedSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 15 },
            { wch: 15 },
            { wch: 15 },
            { wch: 20 },
        ];

        XLSX.utils.book_append_sheet(workbook, detailedSheet, "Detailed Records");
    }

    return workbook;
}
