import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generateExpenseExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    // Create Summary Sheet
    const summaryData = [
        ["EXPENSE REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["SUMMARY METRICS"],
        ["Metric", "Value"],
        [
            "Total Expenses",
            `₹${(data.summary?.totalExpenses || 0).toLocaleString()}`,
        ],
        [
            "Average Expense",
            `₹${(data.summary?.averageExpense || 0).toLocaleString()}`,
        ],
        ["Approval Rate", `${(data.summary?.approvalRate || 0).toFixed(1)}%`],
        ["Pending Claims", data.summary?.pendingCount || 0],
        [""],
    ];

    // Add filter info if applied
    if (filters) {
        if (filters.employeeId) {
            summaryData.push([
                "Filter: Employee",
                data.employees?.find((e: any) => e.id === filters.employeeId)?.name ||
                "All",
            ]);
        }
        if (filters.department) {
            summaryData.push(["Filter: Department", filters.department]);
        }
        summaryData.push([""]);
    }

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 25 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Category Breakdown Sheet
    if (data.categoryBreakdown && data.categoryBreakdown.length > 0) {
        const categoryData = [
            ["Category", "Amount (₹)", "Percentage (%)"],
        ];

        data.categoryBreakdown.forEach((cat: any) => {
            categoryData.push([
                cat.category || "",
                (cat.amount || 0).toLocaleString(),
                cat.percentage || "0",
            ]);
        });

        const categorySheet = XLSX.utils.aoa_to_sheet(categoryData);
        categorySheet["!cols"] = [{ wch: 25 }, { wch: 20 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(workbook, categorySheet, "Category Breakdown");
    }

    // Create All Expenses Sheet
    if (data.recentExpenses && data.recentExpenses.length > 0) {
        const expensesData = [
            [
                "Employee Name",
                "Date",
                "Category",
                "Description",
                "Amount (₹)",
                "Status",
            ],
        ];

        data.recentExpenses.forEach((exp: any) => {
            expensesData.push([
                exp.employeeName || "",
                exp.date || "",
                exp.category || "",
                exp.description || "-",
                (exp.amount || 0).toLocaleString(),
                exp.status || "",
            ]);
        });

        const expensesSheet = XLSX.utils.aoa_to_sheet(expensesData);
        expensesSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 20 },
            { wch: 35 },
            { wch: 15 },
            { wch: 12 },
        ];

        XLSX.utils.book_append_sheet(workbook, expensesSheet, "All Expenses");
    }

    return workbook;
}
