import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generateLeaveExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    const metrics = data.metrics || {
        total_requests: 0,
        approved_requests: 0,
        pending_requests: 0,
        total_employees_on_leave: 0,
        approval_rate: 0,
        total_leave_days: 0,
    };

    const rejectedCount =
        metrics.total_requests -
        metrics.approved_requests -
        metrics.pending_requests;

    // Create Summary Sheet
    const summaryData = [
        ["LEAVE ANALYSIS REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["SUMMARY METRICS"],
        ["Metric", "Value"],
        ["Total Requests", metrics.total_requests],
        ["Approved Requests", metrics.approved_requests],
        ["Pending Requests", metrics.pending_requests],
        ["Rejected Requests", rejectedCount],
        ["Approval Rate", `${metrics.approval_rate}%`],
        ["Total Leave Days", metrics.total_leave_days],
        ["Employees on Leave", metrics.total_employees_on_leave],
        ["Total Leave Types", data.leaveTypes?.length || 0],
        [""],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 25 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Leave Type Distribution Sheet
    if (data.leaveTypes && data.leaveTypes.length > 0) {
        const leaveTypeData = [
            [
                "Leave Type",
                "Total Requests",
                "Approved",
                "Rejected",
                "Pending",
                "Days",
                "% of Total",
            ],
        ];

        const sortedLeaveTypes = [...data.leaveTypes].sort(
            (a, b) => b.request_count - a.request_count,
        );

        sortedLeaveTypes.forEach((type: any) => {
            const percentage =
                metrics.total_requests > 0
                    ? Math.round((type.request_count / metrics.total_requests) * 100)
                    : 0;

            leaveTypeData.push([
                type.leave_type || "",
                type.request_count || 0,
                type.approved_count || 0,
                type.rejected_count || 0,
                type.pending_count || 0,
                type.total_days || 0,
                `${percentage}%`,
            ]);
        });

        const leaveTypeSheet = XLSX.utils.aoa_to_sheet(leaveTypeData);
        leaveTypeSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
            { wch: 12 },
        ];

        XLSX.utils.book_append_sheet(workbook, leaveTypeSheet, "Leave Types");
    }

    // Create Monthly Trend Sheet
    if (data.monthlyTrend && data.monthlyTrend.length > 0) {
        const trendData = [["Month", "Request Count"]];

        data.monthlyTrend.forEach((month: any) => {
            trendData.push([month.month || "", month.count || 0]);
        });

        const trendSheet = XLSX.utils.aoa_to_sheet(trendData);
        trendSheet["!cols"] = [{ wch: 20 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(workbook, trendSheet, "Monthly Trend");
    }

    // Create Employee Statistics Sheet
    if (data.employeeStats && data.employeeStats.length > 0) {
        const employeeData = [
            [
                "Employee Name",
                "Total Requests",
                "Approved",
                "Days Taken",
                "Leave Types",
            ],
        ];

        data.employeeStats.forEach((emp: any) => {
            employeeData.push([
                emp.employee_name || "",
                emp.total_requests || 0,
                emp.approved_requests || 0,
                emp.total_leave_days || 0,
                emp.leave_types || "",
            ]);
        });

        const employeeSheet = XLSX.utils.aoa_to_sheet(employeeData);
        employeeSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 12 },
            { wch: 12 },
            { wch: 30 },
        ];

        XLSX.utils.book_append_sheet(workbook, employeeSheet, "Employee Stats");
    }

    // Create Leave Balance Overview Sheet
    if (data.balances && data.balances.leave_types_balances) {
        const balanceData = [
            ["OVERALL BALANCE"],
            ["Total Available", data.balances.total_leave_balance || 0],
            ["Total Used", data.balances.total_leave_used || 0],
            ["Total Pending", data.balances.total_leave_pending || 0],
            [""],
            ["LEAVE TYPE BALANCES"],
            ["Leave Type", "Available", "Used", "Pending"],
        ];

        data.balances.leave_types_balances.forEach((balance: any) => {
            balanceData.push([
                balance.leave_type || "",
                balance.total_available || 0,
                balance.total_used || 0,
                balance.total_pending || 0,
            ]);
        });

        const balanceSheet = XLSX.utils.aoa_to_sheet(balanceData);
        balanceSheet["!cols"] = [{ wch: 25 }, { wch: 15 }, { wch: 15 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(workbook, balanceSheet, "Leave Balances");
    }

    return workbook;
}
