import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generatePerformanceExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    // Create Summary Sheet
    const summaryData = [
        ["PERFORMANCE REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["PERFORMANCE OVERVIEW"],
        ["Metric", "Value"],
        ["Total Employees", data.summary?.totalEmployees || 0],
        ["Avg Attendance", `${(data.summary?.avgAttendance || 0)}%`],
        [
            "Task Completion Rate",
            `${(data.summary?.avgTaskCompletion || 0)}%`,
        ],
        [
            "Expense Approval Rate",
            `${(data.summary?.avgExpenseApproval || 0)}%`,
        ],
        [""],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 25 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Employee Performance Details Sheet
    if (data.employeePerformance && data.employeePerformance.length > 0) {
        const employeeData = [
            [
                "Employee Name",
                "Employee Number",
                "Attendance (%)",
                "Avg Working Hours",
                "Task Completion (%)",
                "On-Time Tasks (%)",
                "Expense Approval (%)",
            ],
        ];

        data.employeePerformance.forEach((emp: any) => {
            employeeData.push([
                emp.employeeName || "",
                emp.employeeNumber || "",
                (emp.attendance?.onTimeRate || 0),
                (emp.attendance?.avgWorkingHours || 0).toFixed(1),
                (emp.tasks?.completionRate || 0),
                (emp.tasks?.onTimeCompletion || 0),
                (emp.expenses?.approvalRate || 0),
            ]);
        });

        const employeeSheet = XLSX.utils.aoa_to_sheet(employeeData);
        employeeSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 15 },
            { wch: 18 },
            { wch: 18 },
            { wch: 18 },
            { wch: 18 },
        ];

        XLSX.utils.book_append_sheet(workbook, employeeSheet, "Employee Details");
    }

    // Create Department Performance Sheet
    if (data.departmentStats && data.departmentStats.length > 0) {
        const deptData = [
            [
                "Department",
                "Employees",
                "Avg Attendance (%)",
                "Task Completion (%)",
                "Expense Approval (%)",
            ],
        ];

        data.departmentStats.forEach((dept: any) => {
            deptData.push([
                dept.department || "",
                dept.employeeCount || 0,
                (dept.avgAttendance || 0),
                (dept.avgTaskCompletion || 0),
                (dept.avgExpenseApproval || 0),
            ]);
        });

        const deptSheet = XLSX.utils.aoa_to_sheet(deptData);
        deptSheet["!cols"] = [
            { wch: 25 },
            { wch: 12 },
            { wch: 18 },
            { wch: 18 },
            { wch: 18 },
        ];

        XLSX.utils.book_append_sheet(workbook, deptSheet, "Department Stats");
    }

    // Create Top Performers Sheet
    if (data.topPerformers && data.topPerformers.length > 0) {
        const topPerformersData = [
            ["Employee Name", "Department", "Performance Score (%)", "Highlights"],
        ];

        data.topPerformers.forEach((performer: any) => {
            const highlights = (performer.highlights || []).join("; ");
            topPerformersData.push([
                performer.employeeName || "",
                performer.department || "",
                (performer.score || 0),
                highlights,
            ]);
        });

        const topPerformersSheet = XLSX.utils.aoa_to_sheet(topPerformersData);
        topPerformersSheet["!cols"] = [
            { wch: 25 },
            { wch: 20 },
            { wch: 20 },
            { wch: 50 },
        ];

        XLSX.utils.book_append_sheet(workbook, topPerformersSheet, "Top Performers");
    }

    return workbook;
}
