import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generateTaskExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    // Create Summary Sheet
    const summaryData = [
        ["TASK REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["SUMMARY METRICS"],
        ["Metric", "Value"],
        ["Total Tasks", data.summary?.totalTasks || 0],
        ["Completed Tasks", data.summary?.completedTasks || 0],
        [
            "Completion Rate",
            `${(data.summary?.completionRate || 0).toFixed(1)}%`,
        ],
        ["Overdue Tasks", data.summary?.overdueTasks || 0],
        [
            "Avg. Completion Time",
            `${(data.summary?.avgCompletionTime || 0).toFixed(1)} hours`,
        ],
        [""],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 25 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Status Breakdown Sheet
    if (data.statusBreakdown && data.statusBreakdown.length > 0) {
        const statusData = [["Status", "Count", "Percentage (%)"]];

        data.statusBreakdown.forEach((status: any) => {
            statusData.push([
                status.status || "Unknown",
                status.count || 0,
                status.percentage || "0",
            ]);
        });

        const statusSheet = XLSX.utils.aoa_to_sheet(statusData);
        statusSheet["!cols"] = [{ wch: 20 }, { wch: 15 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(workbook, statusSheet, "Status Distribution");
    }

    // Create Priority Breakdown Sheet
    if (data.priorityBreakdown && data.priorityBreakdown.length > 0) {
        const priorityData = [["Priority", "Count", "Percentage (%)"]];

        data.priorityBreakdown.forEach((priority: any) => {
            priorityData.push([
                priority.priority || "Unknown",
                priority.count || 0,
                priority.percentage || "0",
            ]);
        });

        const prioritySheet = XLSX.utils.aoa_to_sheet(priorityData);
        prioritySheet["!cols"] = [{ wch: 20 }, { wch: 15 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(
            workbook,
            prioritySheet,
            "Priority Distribution",
        );
    }

    // Create Employee Performance Sheet
    if (data.employeePerformance && data.employeePerformance.length > 0) {
        const employeeData = [
            [
                "Employee Name",
                "Total Tasks",
                "Completed",
                "On-Time Completion (%)",
                "Avg Completion Time (hrs)",
            ],
        ];

        data.employeePerformance.forEach((emp: any) => {
            employeeData.push([
                emp.employeeName || "Unknown",
                emp.totalTasks || 0,
                emp.completedTasks || 0,
                (emp.onTimeCompletion || 0).toFixed(1),
                (emp.avgCompletionTime || 0).toFixed(1),
            ]);
        });

        const employeeSheet = XLSX.utils.aoa_to_sheet(employeeData);
        employeeSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 15 },
            { wch: 20 },
            { wch: 25 },
        ];

        XLSX.utils.book_append_sheet(workbook, employeeSheet, "Employee Performance");
    }

    return workbook;
}
