import * as XLSX from "xlsx";
import { format } from "date-fns";

interface FilterParams {
    startDate?: Date;
    endDate?: Date;
    employeeId?: number;
    department?: string;
    dateRangePreset?: string;
}

export function generateTravelExcel(
    data: any,
    filters?: FilterParams,
): XLSX.WorkBook {
    const workbook = XLSX.utils.book_new();

    // Create Summary Sheet
    const summaryData = [
        ["TRAVEL REPORT"],
        [""],
        [
            "Generated On:",
            format(new Date(), "MMM dd, yyyy HH:mm"),
            "",
            "Company:",
            data.companyInfo?.name || "",
        ],
        [
            "Date Range:",
            filters?.startDate && filters?.endDate
                ? `${format(filters.startDate, "MMM dd, yyyy")} - ${format(filters.endDate, "MMM dd, yyyy")}`
                : "Last 30 Days",
            "",
            "Generated By:",
            data.adminName || "Group Admin",
        ],
        [""],
        ["SUMMARY METRICS"],
        ["Metric", "Value"],
        ["Total Travelers", data.summary?.totalTravelers || 0],
        ["Total Trips", data.summary?.totalTrips || 0],
        [
            "Total Distance",
            `${(data.summary?.totalDistance || 0).toFixed(1)} km`,
        ],
        [
            "Total Expenses",
            `₹${(data.summary?.totalExpenses || 0).toLocaleString()}`,
        ],
        [
            "Avg Trip Cost",
            `₹${(data.summary?.avgTripCost || 0).toLocaleString()}`,
        ],
        [""],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [
        { wch: 25 },
        { wch: 25 },
        { wch: 5 },
        { wch: 20 },
        { wch: 25 },
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

    // Create Expense Breakdown Sheet
    const expenseBreakdown = data.expenseBreakdown || data.categories || [];
    if (expenseBreakdown.length > 0) {
        const expenseData = [["Category", "Amount (₹)", "Percentage (%)"]];

        expenseBreakdown.forEach((exp: any) => {
            expenseData.push([
                exp.category || "Other",
                (exp.amount || 0).toLocaleString(),
                typeof exp.percentage === "number"
                    ? exp.percentage.toFixed(1)
                    : exp.percentage || "0",
            ]);
        });

        const expenseSheet = XLSX.utils.aoa_to_sheet(expenseData);
        expenseSheet["!cols"] = [{ wch: 25 }, { wch: 20 }, { wch: 15 }];

        XLSX.utils.book_append_sheet(workbook, expenseSheet, "Expense Breakdown");
    }

    // Create Vehicle Statistics Sheet
    const vehicleStats = data.vehicleStats || data.transport || [];
    if (vehicleStats.length > 0) {
        const vehicleData = [
            ["Vehicle Type", "Trips", "Distance (km)", "Expenses (₹)"],
        ];

        vehicleStats.forEach((vehicle: any) => {
            const vehicleType =
                vehicle.vehicleType || vehicle.vehicle_type || "Unknown";
            const tripCount = vehicle.tripCount || vehicle.trip_count || 0;
            const distance =
                vehicle.totalDistance || vehicle.total_distance || 0;
            const expenses =
                vehicle.totalExpenses || vehicle.total_expenses || 0;

            vehicleData.push([
                vehicleType,
                tripCount,
                distance.toFixed(1),
                expenses.toLocaleString(),
            ]);
        });

        const vehicleSheet = XLSX.utils.aoa_to_sheet(vehicleData);
        vehicleSheet["!cols"] = [
            { wch: 20 },
            { wch: 15 },
            { wch: 15 },
            { wch: 20 },
        ];

        XLSX.utils.book_append_sheet(workbook, vehicleSheet, "Vehicle Stats");
    }

    // Create Employee Travel Summary Sheet
    if (data.employeeStats && data.employeeStats.length > 0) {
        const employeeData = [
            [
                "Employee Name",
                "Trips",
                "Distance (km)",
                "Total Expenses (₹)",
                "Avg/Trip (₹)",
            ],
        ];

        data.employeeStats.forEach((emp: any) => {
            employeeData.push([
                emp.employeeName || "Unknown",
                emp.tripCount || 0,
                (emp.totalDistance || 0).toFixed(1),
                (emp.totalExpenses || 0).toLocaleString(),
                (emp.avgExpensePerTrip || 0).toLocaleString(),
            ]);
        });

        const employeeSheet = XLSX.utils.aoa_to_sheet(employeeData);
        employeeSheet["!cols"] = [
            { wch: 25 },
            { wch: 12 },
            { wch: 15 },
            { wch: 20 },
            { wch: 20 },
        ];

        XLSX.utils.book_append_sheet(workbook, employeeSheet, "Employee Summary");
    }

    // Create Recent Trips Sheet
    if (data.recentTrips && data.recentTrips.length > 0) {
        const tripsData = [
            ["Employee Name", "Date", "Description", "Distance (km)", "Expenses (₹)"],
        ];

        data.recentTrips.forEach((trip: any) => {
            tripsData.push([
                trip.employeeName || "Unknown",
                trip.date || "-",
                trip.route || "Travel expense",
                (trip.distance || 0).toFixed(1),
                (trip.expenses || 0).toLocaleString(),
            ]);
        });

        const tripsSheet = XLSX.utils.aoa_to_sheet(tripsData);
        tripsSheet["!cols"] = [
            { wch: 25 },
            { wch: 15 },
            { wch: 35 },
            { wch: 15 },
            { wch: 20 },
        ];

        XLSX.utils.book_append_sheet(workbook, tripsSheet, "Recent Trips");
    }

    return workbook;
}
